# alembic/script.py.mako

"""Add notifications table

Revision ID: 51946547db83
Revises: 9d264b02bba8
Create Date: 2025-08-05 12:45:05.134421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51946547db83'
down_revision = '9d264b02bba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('related_deadline_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['related_deadline_id'], ['deadlines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###